<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridViewEditUpdate.aspx.cs" Inherits="DiscussionForum.GridViewEditUpdate" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" 
            Style="z-index: 100;left: 298px; position: absolute; top: 118px" 
            AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" onrowdeleting="GridView3_RowDeleting" 
            onrowediting="GridView3_RowEditing" onrowupdating="GridView3_RowUpdating" 
            onrowcancelingedit="GridView3_RowCacelingEditing" 
            onselectedindexchanged="GridView3_SelectedIndexChanged">
   <Columns>
   
   <asp:TemplateField HeaderText="ID">
        <ItemTemplate>
            <asp:Label ID ="lblid" Text='<%#Eval("ID") %>' runat="server"></asp:Label>                 
         </ItemTemplate>               
   </asp:TemplateField>

   <asp:TemplateField HeaderText="Name">
         <ItemTemplate><%#Eval("Name") %>      
         </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtname" runat="server" Text ='<% #Eval("Name")%>'></asp:TextBox>         
            </EditItemTemplate>
   </asp:TemplateField>
    
   <asp:TemplateField HeaderText="IsActive">
        <ItemTemplate><%#Eval("IsActive") %></ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtisactive" runat="server" Text='<%#Eval("IsActive") %>'></asp:TextBox>
            </EditItemTemplate>
   </asp:TemplateField>
   
   </Columns>
    </asp:GridView>

    
    </div>
    </form>
</body>
</html>
